// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PinPointTraceInfo.proto

package com.chinamobile.cmss.pinpoint.hbase;

public final class PinPointTraceInfoProtos {
  private PinPointTraceInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PinPointTraceInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // c
    /**
     * <code>optional string pinpoint_trace_id = 101;</code>
     */
    boolean hasPinpointTraceId();
    /**
     * <code>optional string pinpoint_trace_id = 101;</code>
     */
    java.lang.String getPinpointTraceId();
    /**
     * <code>optional string pinpoint_trace_id = 101;</code>
     */
    com.google.protobuf.ByteString
        getPinpointTraceIdBytes();

    // optional int64 pinpoint_span_id = 102;
    /**
     * <code>optional int64 pinpoint_span_id = 102;</code>
     */
    boolean hasPinpointSpanId();
    /**
     * <code>optional int64 pinpoint_span_id = 102;</code>
     */
    long getPinpointSpanId();

    // optional int64 pinpoint_parent_span_id = 103;
    /**
     * <code>optional int64 pinpoint_parent_span_id = 103;</code>
     */
    boolean hasPinpointParentSpanId();
    /**
     * <code>optional int64 pinpoint_parent_span_id = 103;</code>
     */
    long getPinpointParentSpanId();

    // required bool pinpoint_sampled = 104;
    /**
     * <code>required bool pinpoint_sampled = 104;</code>
     */
    boolean hasPinpointSampled();
    /**
     * <code>required bool pinpoint_sampled = 104;</code>
     */
    boolean getPinpointSampled();

    // optional int32 pinpoint_flags = 105;
    /**
     * <code>optional int32 pinpoint_flags = 105;</code>
     */
    boolean hasPinpointFlags();
    /**
     * <code>optional int32 pinpoint_flags = 105;</code>
     */
    int getPinpointFlags();

    // optional string pinpoint_parent_application_name = 106;
    /**
     * <code>optional string pinpoint_parent_application_name = 106;</code>
     */
    boolean hasPinpointParentApplicationName();
    /**
     * <code>optional string pinpoint_parent_application_name = 106;</code>
     */
    java.lang.String getPinpointParentApplicationName();
    /**
     * <code>optional string pinpoint_parent_application_name = 106;</code>
     */
    com.google.protobuf.ByteString
        getPinpointParentApplicationNameBytes();

    // optional int32 pinpoint_parent_application_type = 107;
    /**
     * <code>optional int32 pinpoint_parent_application_type = 107;</code>
     */
    boolean hasPinpointParentApplicationType();
    /**
     * <code>optional int32 pinpoint_parent_application_type = 107;</code>
     */
    int getPinpointParentApplicationType();

    // optional string pinpoint_host = 108;
    /**
     * <code>optional string pinpoint_host = 108;</code>
     */
    boolean hasPinpointHost();
    /**
     * <code>optional string pinpoint_host = 108;</code>
     */
    java.lang.String getPinpointHost();
    /**
     * <code>optional string pinpoint_host = 108;</code>
     */
    com.google.protobuf.ByteString
        getPinpointHostBytes();
  }
  /**
   * Protobuf type {@code PinPointTraceInfo}
   *
   * <pre>
   **
   * Content of the '/hbase/hbaseid', cluster id, znode.
   * Also cluster of the ${HBASE_ROOTDIR}/hbase.id file.
   * </pre>
   */
  public static final class PinPointTraceInfo extends
      com.google.protobuf.GeneratedMessage
      implements PinPointTraceInfoOrBuilder {
    // Use PinPointTraceInfo.newBuilder() to construct.
    private PinPointTraceInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PinPointTraceInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PinPointTraceInfo defaultInstance;
    public static PinPointTraceInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PinPointTraceInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PinPointTraceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 810: {
              bitField0_ |= 0x00000001;
              pinpointTraceId_ = input.readBytes();
              break;
            }
            case 816: {
              bitField0_ |= 0x00000002;
              pinpointSpanId_ = input.readInt64();
              break;
            }
            case 824: {
              bitField0_ |= 0x00000004;
              pinpointParentSpanId_ = input.readInt64();
              break;
            }
            case 832: {
              bitField0_ |= 0x00000008;
              pinpointSampled_ = input.readBool();
              break;
            }
            case 840: {
              bitField0_ |= 0x00000010;
              pinpointFlags_ = input.readInt32();
              break;
            }
            case 850: {
              bitField0_ |= 0x00000020;
              pinpointParentApplicationName_ = input.readBytes();
              break;
            }
            case 856: {
              bitField0_ |= 0x00000040;
              pinpointParentApplicationType_ = input.readInt32();
              break;
            }
            case 866: {
              bitField0_ |= 0x00000080;
              pinpointHost_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.internal_static_PinPointTraceInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.internal_static_PinPointTraceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo.class, com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PinPointTraceInfo> PARSER =
        new com.google.protobuf.AbstractParser<PinPointTraceInfo>() {
      public PinPointTraceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PinPointTraceInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PinPointTraceInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string pinpoint_trace_id = 101;
    public static final int PINPOINT_TRACE_ID_FIELD_NUMBER = 101;
    private java.lang.Object pinpointTraceId_;
    /**
     * <code>optional string pinpoint_trace_id = 101;</code>
     */
    public boolean hasPinpointTraceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string pinpoint_trace_id = 101;</code>
     */
    public java.lang.String getPinpointTraceId() {
      java.lang.Object ref = pinpointTraceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pinpointTraceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pinpoint_trace_id = 101;</code>
     */
    public com.google.protobuf.ByteString
        getPinpointTraceIdBytes() {
      java.lang.Object ref = pinpointTraceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pinpointTraceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 pinpoint_span_id = 102;
    public static final int PINPOINT_SPAN_ID_FIELD_NUMBER = 102;
    private long pinpointSpanId_;
    /**
     * <code>optional int64 pinpoint_span_id = 102;</code>
     */
    public boolean hasPinpointSpanId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 pinpoint_span_id = 102;</code>
     */
    public long getPinpointSpanId() {
      return pinpointSpanId_;
    }

    // optional int64 pinpoint_parent_span_id = 103;
    public static final int PINPOINT_PARENT_SPAN_ID_FIELD_NUMBER = 103;
    private long pinpointParentSpanId_;
    /**
     * <code>optional int64 pinpoint_parent_span_id = 103;</code>
     */
    public boolean hasPinpointParentSpanId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 pinpoint_parent_span_id = 103;</code>
     */
    public long getPinpointParentSpanId() {
      return pinpointParentSpanId_;
    }

    // required bool pinpoint_sampled = 104;
    public static final int PINPOINT_SAMPLED_FIELD_NUMBER = 104;
    private boolean pinpointSampled_;
    /**
     * <code>required bool pinpoint_sampled = 104;</code>
     */
    public boolean hasPinpointSampled() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool pinpoint_sampled = 104;</code>
     */
    public boolean getPinpointSampled() {
      return pinpointSampled_;
    }

    // optional int32 pinpoint_flags = 105;
    public static final int PINPOINT_FLAGS_FIELD_NUMBER = 105;
    private int pinpointFlags_;
    /**
     * <code>optional int32 pinpoint_flags = 105;</code>
     */
    public boolean hasPinpointFlags() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 pinpoint_flags = 105;</code>
     */
    public int getPinpointFlags() {
      return pinpointFlags_;
    }

    // optional string pinpoint_parent_application_name = 106;
    public static final int PINPOINT_PARENT_APPLICATION_NAME_FIELD_NUMBER = 106;
    private java.lang.Object pinpointParentApplicationName_;
    /**
     * <code>optional string pinpoint_parent_application_name = 106;</code>
     */
    public boolean hasPinpointParentApplicationName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string pinpoint_parent_application_name = 106;</code>
     */
    public java.lang.String getPinpointParentApplicationName() {
      java.lang.Object ref = pinpointParentApplicationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pinpointParentApplicationName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pinpoint_parent_application_name = 106;</code>
     */
    public com.google.protobuf.ByteString
        getPinpointParentApplicationNameBytes() {
      java.lang.Object ref = pinpointParentApplicationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pinpointParentApplicationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 pinpoint_parent_application_type = 107;
    public static final int PINPOINT_PARENT_APPLICATION_TYPE_FIELD_NUMBER = 107;
    private int pinpointParentApplicationType_;
    /**
     * <code>optional int32 pinpoint_parent_application_type = 107;</code>
     */
    public boolean hasPinpointParentApplicationType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 pinpoint_parent_application_type = 107;</code>
     */
    public int getPinpointParentApplicationType() {
      return pinpointParentApplicationType_;
    }

    // optional string pinpoint_host = 108;
    public static final int PINPOINT_HOST_FIELD_NUMBER = 108;
    private java.lang.Object pinpointHost_;
    /**
     * <code>optional string pinpoint_host = 108;</code>
     */
    public boolean hasPinpointHost() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string pinpoint_host = 108;</code>
     */
    public java.lang.String getPinpointHost() {
      java.lang.Object ref = pinpointHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pinpointHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pinpoint_host = 108;</code>
     */
    public com.google.protobuf.ByteString
        getPinpointHostBytes() {
      java.lang.Object ref = pinpointHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pinpointHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      pinpointTraceId_ = "";
      pinpointSpanId_ = 0L;
      pinpointParentSpanId_ = 0L;
      pinpointSampled_ = false;
      pinpointFlags_ = 0;
      pinpointParentApplicationName_ = "";
      pinpointParentApplicationType_ = 0;
      pinpointHost_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPinpointSampled()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(101, getPinpointTraceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(102, pinpointSpanId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(103, pinpointParentSpanId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(104, pinpointSampled_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(105, pinpointFlags_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(106, getPinpointParentApplicationNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(107, pinpointParentApplicationType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(108, getPinpointHostBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(101, getPinpointTraceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(102, pinpointSpanId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(103, pinpointParentSpanId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(104, pinpointSampled_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(105, pinpointFlags_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(106, getPinpointParentApplicationNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(107, pinpointParentApplicationType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(108, getPinpointHostBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo)) {
        return super.equals(obj);
      }
      com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo other = (com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo) obj;

      boolean result = true;
      result = result && (hasPinpointTraceId() == other.hasPinpointTraceId());
      if (hasPinpointTraceId()) {
        result = result && getPinpointTraceId()
            .equals(other.getPinpointTraceId());
      }
      result = result && (hasPinpointSpanId() == other.hasPinpointSpanId());
      if (hasPinpointSpanId()) {
        result = result && (getPinpointSpanId()
            == other.getPinpointSpanId());
      }
      result = result && (hasPinpointParentSpanId() == other.hasPinpointParentSpanId());
      if (hasPinpointParentSpanId()) {
        result = result && (getPinpointParentSpanId()
            == other.getPinpointParentSpanId());
      }
      result = result && (hasPinpointSampled() == other.hasPinpointSampled());
      if (hasPinpointSampled()) {
        result = result && (getPinpointSampled()
            == other.getPinpointSampled());
      }
      result = result && (hasPinpointFlags() == other.hasPinpointFlags());
      if (hasPinpointFlags()) {
        result = result && (getPinpointFlags()
            == other.getPinpointFlags());
      }
      result = result && (hasPinpointParentApplicationName() == other.hasPinpointParentApplicationName());
      if (hasPinpointParentApplicationName()) {
        result = result && getPinpointParentApplicationName()
            .equals(other.getPinpointParentApplicationName());
      }
      result = result && (hasPinpointParentApplicationType() == other.hasPinpointParentApplicationType());
      if (hasPinpointParentApplicationType()) {
        result = result && (getPinpointParentApplicationType()
            == other.getPinpointParentApplicationType());
      }
      result = result && (hasPinpointHost() == other.hasPinpointHost());
      if (hasPinpointHost()) {
        result = result && getPinpointHost()
            .equals(other.getPinpointHost());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPinpointTraceId()) {
        hash = (37 * hash) + PINPOINT_TRACE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPinpointTraceId().hashCode();
      }
      if (hasPinpointSpanId()) {
        hash = (37 * hash) + PINPOINT_SPAN_ID_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getPinpointSpanId());
      }
      if (hasPinpointParentSpanId()) {
        hash = (37 * hash) + PINPOINT_PARENT_SPAN_ID_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getPinpointParentSpanId());
      }
      if (hasPinpointSampled()) {
        hash = (37 * hash) + PINPOINT_SAMPLED_FIELD_NUMBER;
        hash = (53 * hash) + hashBoolean(getPinpointSampled());
      }
      if (hasPinpointFlags()) {
        hash = (37 * hash) + PINPOINT_FLAGS_FIELD_NUMBER;
        hash = (53 * hash) + getPinpointFlags();
      }
      if (hasPinpointParentApplicationName()) {
        hash = (37 * hash) + PINPOINT_PARENT_APPLICATION_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getPinpointParentApplicationName().hashCode();
      }
      if (hasPinpointParentApplicationType()) {
        hash = (37 * hash) + PINPOINT_PARENT_APPLICATION_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getPinpointParentApplicationType();
      }
      if (hasPinpointHost()) {
        hash = (37 * hash) + PINPOINT_HOST_FIELD_NUMBER;
        hash = (53 * hash) + getPinpointHost().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PinPointTraceInfo}
     *
     * <pre>
     **
     * Content of the '/hbase/hbaseid', cluster id, znode.
     * Also cluster of the ${HBASE_ROOTDIR}/hbase.id file.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.internal_static_PinPointTraceInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.internal_static_PinPointTraceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo.class, com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo.Builder.class);
      }

      // Construct using com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pinpointTraceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pinpointSpanId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        pinpointParentSpanId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        pinpointSampled_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        pinpointFlags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        pinpointParentApplicationName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        pinpointParentApplicationType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        pinpointHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.internal_static_PinPointTraceInfo_descriptor;
      }

      public com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo getDefaultInstanceForType() {
        return com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo.getDefaultInstance();
      }

      public com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo build() {
        com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo buildPartial() {
        com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo result = new com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pinpointTraceId_ = pinpointTraceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pinpointSpanId_ = pinpointSpanId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pinpointParentSpanId_ = pinpointParentSpanId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pinpointSampled_ = pinpointSampled_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.pinpointFlags_ = pinpointFlags_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.pinpointParentApplicationName_ = pinpointParentApplicationName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.pinpointParentApplicationType_ = pinpointParentApplicationType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.pinpointHost_ = pinpointHost_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo) {
          return mergeFrom((com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo other) {
        if (other == com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo.getDefaultInstance()) return this;
        if (other.hasPinpointTraceId()) {
          bitField0_ |= 0x00000001;
          pinpointTraceId_ = other.pinpointTraceId_;
          onChanged();
        }
        if (other.hasPinpointSpanId()) {
          setPinpointSpanId(other.getPinpointSpanId());
        }
        if (other.hasPinpointParentSpanId()) {
          setPinpointParentSpanId(other.getPinpointParentSpanId());
        }
        if (other.hasPinpointSampled()) {
          setPinpointSampled(other.getPinpointSampled());
        }
        if (other.hasPinpointFlags()) {
          setPinpointFlags(other.getPinpointFlags());
        }
        if (other.hasPinpointParentApplicationName()) {
          bitField0_ |= 0x00000020;
          pinpointParentApplicationName_ = other.pinpointParentApplicationName_;
          onChanged();
        }
        if (other.hasPinpointParentApplicationType()) {
          setPinpointParentApplicationType(other.getPinpointParentApplicationType());
        }
        if (other.hasPinpointHost()) {
          bitField0_ |= 0x00000080;
          pinpointHost_ = other.pinpointHost_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPinpointSampled()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.chinamobile.cmss.pinpoint.hbase.PinPointTraceInfoProtos.PinPointTraceInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string pinpoint_trace_id = 101;
      private java.lang.Object pinpointTraceId_ = "";
      /**
       * <code>optional string pinpoint_trace_id = 101;</code>
       */
      public boolean hasPinpointTraceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string pinpoint_trace_id = 101;</code>
       */
      public java.lang.String getPinpointTraceId() {
        java.lang.Object ref = pinpointTraceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pinpointTraceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pinpoint_trace_id = 101;</code>
       */
      public com.google.protobuf.ByteString
          getPinpointTraceIdBytes() {
        java.lang.Object ref = pinpointTraceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pinpointTraceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pinpoint_trace_id = 101;</code>
       */
      public Builder setPinpointTraceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pinpointTraceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinpoint_trace_id = 101;</code>
       */
      public Builder clearPinpointTraceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pinpointTraceId_ = getDefaultInstance().getPinpointTraceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinpoint_trace_id = 101;</code>
       */
      public Builder setPinpointTraceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pinpointTraceId_ = value;
        onChanged();
        return this;
      }

      // optional int64 pinpoint_span_id = 102;
      private long pinpointSpanId_ ;
      /**
       * <code>optional int64 pinpoint_span_id = 102;</code>
       */
      public boolean hasPinpointSpanId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 pinpoint_span_id = 102;</code>
       */
      public long getPinpointSpanId() {
        return pinpointSpanId_;
      }
      /**
       * <code>optional int64 pinpoint_span_id = 102;</code>
       */
      public Builder setPinpointSpanId(long value) {
        bitField0_ |= 0x00000002;
        pinpointSpanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 pinpoint_span_id = 102;</code>
       */
      public Builder clearPinpointSpanId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pinpointSpanId_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 pinpoint_parent_span_id = 103;
      private long pinpointParentSpanId_ ;
      /**
       * <code>optional int64 pinpoint_parent_span_id = 103;</code>
       */
      public boolean hasPinpointParentSpanId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 pinpoint_parent_span_id = 103;</code>
       */
      public long getPinpointParentSpanId() {
        return pinpointParentSpanId_;
      }
      /**
       * <code>optional int64 pinpoint_parent_span_id = 103;</code>
       */
      public Builder setPinpointParentSpanId(long value) {
        bitField0_ |= 0x00000004;
        pinpointParentSpanId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 pinpoint_parent_span_id = 103;</code>
       */
      public Builder clearPinpointParentSpanId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pinpointParentSpanId_ = 0L;
        onChanged();
        return this;
      }

      // required bool pinpoint_sampled = 104;
      private boolean pinpointSampled_ ;
      /**
       * <code>required bool pinpoint_sampled = 104;</code>
       */
      public boolean hasPinpointSampled() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool pinpoint_sampled = 104;</code>
       */
      public boolean getPinpointSampled() {
        return pinpointSampled_;
      }
      /**
       * <code>required bool pinpoint_sampled = 104;</code>
       */
      public Builder setPinpointSampled(boolean value) {
        bitField0_ |= 0x00000008;
        pinpointSampled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool pinpoint_sampled = 104;</code>
       */
      public Builder clearPinpointSampled() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pinpointSampled_ = false;
        onChanged();
        return this;
      }

      // optional int32 pinpoint_flags = 105;
      private int pinpointFlags_ ;
      /**
       * <code>optional int32 pinpoint_flags = 105;</code>
       */
      public boolean hasPinpointFlags() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 pinpoint_flags = 105;</code>
       */
      public int getPinpointFlags() {
        return pinpointFlags_;
      }
      /**
       * <code>optional int32 pinpoint_flags = 105;</code>
       */
      public Builder setPinpointFlags(int value) {
        bitField0_ |= 0x00000010;
        pinpointFlags_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pinpoint_flags = 105;</code>
       */
      public Builder clearPinpointFlags() {
        bitField0_ = (bitField0_ & ~0x00000010);
        pinpointFlags_ = 0;
        onChanged();
        return this;
      }

      // optional string pinpoint_parent_application_name = 106;
      private java.lang.Object pinpointParentApplicationName_ = "";
      /**
       * <code>optional string pinpoint_parent_application_name = 106;</code>
       */
      public boolean hasPinpointParentApplicationName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string pinpoint_parent_application_name = 106;</code>
       */
      public java.lang.String getPinpointParentApplicationName() {
        java.lang.Object ref = pinpointParentApplicationName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pinpointParentApplicationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pinpoint_parent_application_name = 106;</code>
       */
      public com.google.protobuf.ByteString
          getPinpointParentApplicationNameBytes() {
        java.lang.Object ref = pinpointParentApplicationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pinpointParentApplicationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pinpoint_parent_application_name = 106;</code>
       */
      public Builder setPinpointParentApplicationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pinpointParentApplicationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinpoint_parent_application_name = 106;</code>
       */
      public Builder clearPinpointParentApplicationName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pinpointParentApplicationName_ = getDefaultInstance().getPinpointParentApplicationName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinpoint_parent_application_name = 106;</code>
       */
      public Builder setPinpointParentApplicationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        pinpointParentApplicationName_ = value;
        onChanged();
        return this;
      }

      // optional int32 pinpoint_parent_application_type = 107;
      private int pinpointParentApplicationType_ ;
      /**
       * <code>optional int32 pinpoint_parent_application_type = 107;</code>
       */
      public boolean hasPinpointParentApplicationType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 pinpoint_parent_application_type = 107;</code>
       */
      public int getPinpointParentApplicationType() {
        return pinpointParentApplicationType_;
      }
      /**
       * <code>optional int32 pinpoint_parent_application_type = 107;</code>
       */
      public Builder setPinpointParentApplicationType(int value) {
        bitField0_ |= 0x00000040;
        pinpointParentApplicationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 pinpoint_parent_application_type = 107;</code>
       */
      public Builder clearPinpointParentApplicationType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pinpointParentApplicationType_ = 0;
        onChanged();
        return this;
      }

      // optional string pinpoint_host = 108;
      private java.lang.Object pinpointHost_ = "";
      /**
       * <code>optional string pinpoint_host = 108;</code>
       */
      public boolean hasPinpointHost() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string pinpoint_host = 108;</code>
       */
      public java.lang.String getPinpointHost() {
        java.lang.Object ref = pinpointHost_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pinpointHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pinpoint_host = 108;</code>
       */
      public com.google.protobuf.ByteString
          getPinpointHostBytes() {
        java.lang.Object ref = pinpointHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pinpointHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pinpoint_host = 108;</code>
       */
      public Builder setPinpointHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pinpointHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinpoint_host = 108;</code>
       */
      public Builder clearPinpointHost() {
        bitField0_ = (bitField0_ & ~0x00000080);
        pinpointHost_ = getDefaultInstance().getPinpointHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pinpoint_host = 108;</code>
       */
      public Builder setPinpointHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        pinpointHost_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PinPointTraceInfo)
    }

    static {
      defaultInstance = new PinPointTraceInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PinPointTraceInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PinPointTraceInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PinPointTraceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027PinPointTraceInfo.proto\"\206\002\n\021PinPointTr" +
      "aceInfo\022\031\n\021pinpoint_trace_id\030e \001(\t\022\030\n\020pi" +
      "npoint_span_id\030f \001(\003\022\037\n\027pinpoint_parent_" +
      "span_id\030g \001(\003\022\030\n\020pinpoint_sampled\030h \002(\010\022" +
      "\026\n\016pinpoint_flags\030i \001(\005\022(\n pinpoint_pare" +
      "nt_application_name\030j \001(\t\022(\n pinpoint_pa" +
      "rent_application_type\030k \001(\005\022\025\n\rpinpoint_" +
      "host\030l \001(\tBC\n#com.chinamobile.cmss.pinpo" +
      "int.hbaseB\027PinPointTraceInfoProtosH\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PinPointTraceInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PinPointTraceInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PinPointTraceInfo_descriptor,
              new java.lang.String[] { "PinpointTraceId", "PinpointSpanId", "PinpointParentSpanId", "PinpointSampled", "PinpointFlags", "PinpointParentApplicationName", "PinpointParentApplicationType", "PinpointHost", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
